/// Web 运行时模板（JavaScript）。
///
/// 这是嵌入到产物 `runtime.js` 中的 JS 解释器+UI 渲染器，负责：
/// - 加载 `ir.json` 中的项目 IR
/// - 渲染 UI 树为 DOM（Text / Column / Row / Container / Button / Image 等）
/// - 执行节点函数 DAG（控制流遍历 + `#` 引用解析）
/// - 处理 UI 事件触发函数
/// - 函数执行后回写 UI 绑定
///
/// v1 实现常见节点类型的 JS 解释（变量、算术、逻辑、字符串、If、Loop、
/// function_call、return、variable_get/set），其余节点（db_*, plugin_*）
/// 在 Web 端降级为 no-op + console.warn。
class WebRuntimeTemplate {
  WebRuntimeTemplate._();

  /// 生成 runtime.js 内容。
  static String runtimeJs() {
    return '''
// NodeVisual Web Runtime v1
// Auto-generated by NodeVisual App Builder. Interprets IR + renders UI tree.
(function () {
  "use strict";

  // ====== IR 加载 ======
  let IR = null;
  let PROJECT = null;
  const BINDING_REGISTRY = new Map(); // uiNodeId -> { fn: Function, domEl: Element }

  // 页面级函数 outputs 缓存（key = funcId, value = { state, outputs, error }）。
  // 供同页面 UI 组件的 #funcVar 引用按时间线规则读取。声明在此处以保证
  // readBindingValue 可引用（const 不会被运行时函数提升）。
  const PAGE_FUNC_OUTPUTS = new Map();

  async function loadIR() {
    // ir.json 与 runtime.js 同目录
    const resp = await fetch("ir.json", { cache: "no-store" });
    if (!resp.ok) throw new Error("Failed to load ir.json: " + resp.status);
    IR = await resp.json();
    PROJECT = IR;
  }

  // ====== 类型与作用域 ======
  class Scope {
    constructor(parent) {
      this.parent = parent || null;
      this.nodeOutputs = new Map(); // "nodeId.outputName" -> value
      this.funcVars = new Map();
      this.projVars = new Map();
      this.inputs = new Map();
    }
    setOutput(nodeId, name, value) {
      this.nodeOutputs.set(nodeId + "." + name, value);
    }
    getOutput(nodeId, name) {
      const k = nodeId + "." + name;
      if (this.nodeOutputs.has(k)) return this.nodeOutputs.get(k);
      if (this.parent) return this.parent.getOutput(nodeId, name);
      return undefined;
    }
    setFuncVar(id, v) { this.funcVars.set(id, v); }
    getFuncVar(id) {
      if (this.funcVars.has(id)) return this.funcVars.get(id);
      if (this.parent) return this.parent.getFuncVar(id);
      return undefined;
    }
    setProjVar(id, v) { this.projVars.set(id, v); }
    getProjVar(id) {
      if (this.projVars.has(id)) return this.projVars.get(id);
      if (this.parent) return this.parent.getProjVar(id);
      return undefined;
    }
  }

  // ====== # 引用解析 ======
  function resolveRef(value, scope) {
    if (value && typeof value === "object" && value.ref) {
      const r = value.ref;
      if (r.source === "upstream") {
        return scope.getOutput(r.nodeId, r.outputName);
      } else if (r.source === "funcVar") {
        return scope.getFuncVar(r.varId);
      } else if (r.source === "projVar") {
        return scope.getProjVar(r.varId);
      }
      return undefined;
    }
    return value;
  }

  // ====== 节点执行 ======
  function findFunction(funcIdOrName) {
    if (!PROJECT || !PROJECT.functions) return null;
    return PROJECT.functions.find(f => f.id === funcIdOrName || f.name === funcIdOrName);
  }

  function findEntryNode(func) {
    if (!func || !func.nodes) return null;
    const inDeg = new Map();
    func.nodes.forEach(n => inDeg.set(n.id, 0));
    (func.controlEdges || []).forEach(e => {
      if (inDeg.has(e.toNode)) inDeg.set(e.toNode, inDeg.get(e.toNode) + 1);
    });
    // 取无入边中第一个
    for (const n of func.nodes) {
      if (inDeg.get(n.id) === 0) return n;
    }
    return func.nodes[0] || null;
  }

  function findNextNode(func, currentId, controlOutputName) {
    if (!func.controlEdges) return null;
    // 取匹配 fromNode + fromPort 的第一条未访问边
    const edges = func.controlEdges.filter(e =>
      e.fromNode === currentId && (e.fromPort === controlOutputName || !controlOutputName)
    );
    if (edges.length === 0) return null;
    return edges[0].toNode;
  }

  const MAX_STEPS = 10000;

  async function runFunction(func, inputs) {
    const scope = new Scope();
    inputs = inputs || {};
    // 项目变量默认值
    (PROJECT.projectVars || []).forEach(v => scope.setProjVar(v.id, v.defaultValue));
    // 函数变量入参
    Object.keys(inputs).forEach(k => {
      const fv = (func.funcVars || []).find(v => v.name === k);
      if (fv) scope.setFuncVar(fv.id, inputs[k]);
    });
    (func.funcVars || []).forEach(v => {
      if (!inputs[v.name]) scope.setFuncVar(v.id, v.defaultValue);
    });

    let node = findEntryNode(func);
    let steps = 0;
    let lastControlOut = null;
    while (node && steps < MAX_STEPS) {
      steps++;
      const result = await executeNode(node, func, scope);
      if (result.error) return { error: result.error };
      if (result.return !== undefined) return { outputs: result.return };
      // 记录节点所有 dataOutputs 到 scope
      if (node.dataOutputs) {
        for (const out of node.dataOutputs) {
          if (result.outputs && result.outputs[out.name] !== undefined) {
            scope.setOutput(node.id, out.name, result.outputs[out.name]);
          }
        }
      }
      lastControlOut = result.controlOutput || null;
      const nextId = findNextNode(func, node.id, lastControlOut);
      if (!nextId) break;
      node = func.nodes.find(n => n.id === nextId);
    }
    return { outputs: collectOutputs(scope) };
  }

  function collectOutputs(scope) {
    // 取所有 nodeOutputs 作为返回值
    const out = {};
    for (const [k, v] of scope.nodeOutputs.entries()) {
      out[k] = v;
    }
    return out;
  }

  async function executeNode(node, func, scope) {
    const params = node.params || {};
    switch (node.kind) {
      case "variable_set": {
        const v = resolveRef(params.value, scope);
        if (params.varName) scope.setFuncVar(params.varName, v);
        return { outputs: { value: v } };
      }
      case "variable_get": {
        const v = scope.getFuncVar(params.varName);
        return { outputs: { value: v } };
      }
      case "arithmetic": {
        const a = resolveRef(params.a, scope);
        const b = resolveRef(params.b, scope);
        const op = params.op || "+";
        let r;
        switch (op) {
          case "+": r = (a || 0) + (b || 0); break;
          case "-": r = (a || 0) - (b || 0); break;
          case "*": r = (a || 0) * (b || 0); break;
          case "/": r = (b || 0) === 0 ? null : (a || 0) / (b || 0); break;
          case "%": r = (b || 0) === 0 ? null : (a || 0) % (b || 0); break;
          default: r = null;
        }
        return { outputs: { result: r } };
      }
      case "logic": {
        const a = resolveRef(params.a, scope);
        const b = resolveRef(params.b, scope);
        const op = params.op || "&&";
        let r;
        switch (op) {
          case "&&": r = !!a && !!b; break;
          case "||": r = !!a || !!b; break;
          case "!": r = !a; break;
          case "==": r = a === b; break;
          case "!=": r = a !== b; break;
          case ">": r = a > b; break;
          case "<": r = a < b; break;
          case ">=": r = a >= b; break;
          case "<=": r = a <= b; break;
          default: r = false;
        }
        return { outputs: { result: r } };
      }
      case "string_op": {
        const a = String(resolveRef(params.a, scope) ?? "");
        const b = String(resolveRef(params.b, scope) ?? "");
        const op = params.op || "concat";
        let r;
        switch (op) {
          case "concat": r = a + b; break;
          case "upper": r = a.toUpperCase(); break;
          case "lower": r = a.toLowerCase(); break;
          case "substring": {
            const start = Number(resolveRef(params.start, scope) || 0);
            const end = Number(resolveRef(params.end, scope) || a.length);
            r = a.substring(start, end); break;
          }
          case "length": r = a.length; break;
          case "contains": r = a.includes(b); break;
          case "replace": r = a.split(b).join(String(resolveRef(params.replacement, scope) || "")); break;
          default: r = a;
        }
        return { outputs: { result: r } };
      }
      case "if": {
        const cond = resolveRef(params.condition, scope);
        const cases = params.cases || [];
        for (const c of cases) {
          const cv = resolveRef(c.value, scope);
          // case value 为 null 表示 default/else
          if (c.value === null || c.value === undefined || cv === cond) {
            return { controlOutput: c.label || "true", outputs: {} };
          }
        }
        return { controlOutput: cond ? "true" : "false", outputs: {} };
      }
      case "loop": {
        // v1: 简化为 for-each over list
        const list = resolveRef(params.list, scope) || [];
        const bodyPort = "body";
        const completedPort = "completed";
        // 简化：直接展开循环（不真执行子图，仅登记 item/index）
        let idx = 0;
        for (const item of list) {
          scope.setOutput(node.id, "item", item);
          scope.setOutput(node.id, "index", idx++);
        }
        return { controlOutput: completedPort, outputs: { count: idx } };
      }
      case "function_call": {
        const targetFn = findFunction(params.functionId || params.functionName);
        if (!targetFn) return { error: "Function not found: " + (params.functionId || params.functionName) };
        const callInputs = {};
        Object.keys(params.inputs || {}).forEach(k => {
          callInputs[k] = resolveRef(params.inputs[k], scope);
        });
        const r = await runFunction(targetFn, callInputs);
        if (r.error) return { error: r.error };
        return { outputs: { result: r.outputs } };
      }
      case "return": {
        const v = resolveRef(params.value, scope);
        return { return: v };
      }
      case "literal": {
        return { outputs: { value: params.value } };
      }
      default:
        if (node.kind && node.kind.indexOf("db_") === 0) {
          console.warn("[NodeVisual] DB node not supported in Web runtime: " + node.kind);
          return { outputs: {} };
        }
        if (node.kind && node.kind.indexOf("plugin_") === 0) {
          console.warn("[NodeVisual] Plugin node not supported in Web runtime: " + node.kind);
          return { outputs: {} };
        }
        console.warn("[NodeVisual] Unknown node kind: " + node.kind);
        return { outputs: {} };
    }
  }

  // ====== UI 渲染 ======
  function renderUI() {
    if (!PROJECT || !PROJECT.ui || !PROJECT.ui.tree) return;
    const root = document.getElementById("app-root");
    if (!root) return;
    root.innerHTML = "";
    const uiRoot = PROJECT.ui.tree;
    const el = renderNode(uiRoot, null);
    if (el) root.appendChild(el);
  }

  function renderNode(uiNode, parent) {
    if (!uiNode || !uiNode.type) return null;
    let el;
    switch (uiNode.type) {
      case "Column":
        el = document.createElement("div");
        el.style.display = "flex";
        el.style.flexDirection = "column";
        el.style.gap = (uiNode.props.gap || 8) + "px";
        break;
      case "Row":
        el = document.createElement("div");
        el.style.display = "flex";
        el.style.flexDirection = "row";
        el.style.gap = (uiNode.props.gap || 8) + "px";
        break;
      case "Container":
        el = document.createElement("div");
        if (uiNode.props.padding) el.style.padding = uiNode.props.padding + "px";
        if (uiNode.props.color) el.style.backgroundColor = uiNode.props.color;
        if (uiNode.props.width) el.style.width = uiNode.props.width + "px";
        if (uiNode.props.height) el.style.height = uiNode.props.height + "px";
        break;
      case "Text":
        el = document.createElement("span");
        el.textContent = String(uiNode.props.text || "");
        if (uiNode.props.fontSize) el.style.fontSize = uiNode.props.fontSize + "px";
        if (uiNode.props.color) el.style.color = uiNode.props.color;
        if (uiNode.props.fontWeight) el.style.fontWeight = uiNode.props.fontWeight;
        break;
      case "ElevatedButton":
        el = document.createElement("button");
        el.textContent = String(uiNode.props.label || "Button");
        if (uiNode.props.onTap) {
          el.addEventListener("click", () => triggerFunction(uiNode.props.onTap));
        }
        break;
      case "TextField":
        el = document.createElement("input");
        el.type = "text";
        el.placeholder = String(uiNode.props.placeholder || "");
        break;
      case "Image":
        el = document.createElement("img");
        if (uiNode.props.src) el.src = uiNode.props.src;
        el.alt = String(uiNode.props.alt || "");
        break;
      case "Scaffold":
        el = document.createElement("div");
        break;
      default:
        el = document.createElement("div");
        el.setAttribute("data-type", uiNode.type);
    }
    el.setAttribute("data-ui-id", uiNode.id || "");

    // 应用静态 props
    if (uiNode.props) {
      Object.keys(uiNode.props).forEach(k => {
        if (k === "text" || k === "label" || k === "placeholder" || k === "src") return;
        // 其他 prop 由 case 内已处理
      });
    }

    // 应用绑定
    if (uiNode.bindings) {
      applyBindings(el, uiNode);
    }

    // 触发点：加载时
    if (uiNode.props && uiNode.props.onLoad) {
      setTimeout(() => triggerFunction(uiNode.props.onLoad), 0);
    }

    // 子节点
    if (uiNode.children) {
      uiNode.children.forEach(child => {
        const childEl = renderNode(child, el);
        if (childEl) el.appendChild(childEl);
      });
    }
    return el;
  }

  function applyBindings(el, uiNode) {
    Object.keys(uiNode.bindings || {}).forEach(propName => {
      const binding = uiNode.bindings[propName];
      if (!binding || !binding.ref) return;
      // 初始值
      const value = readBindingValue(binding.ref);
      if (value !== undefined) {
        applyProp(el, propName, value);
      }
      // 注册到 binding registry（后续函数执行后回写）
      const id = uiNode.id;
      if (!BINDING_REGISTRY.has(id)) BINDING_REGISTRY.set(id, []);
      BINDING_REGISTRY.get(id).push({ el, propName, ref: binding.ref });
    });
  }

  function applyProp(el, propName, value) {
    switch (propName) {
      case "text":
      case "label":
        if (el.tagName === "BUTTON" || el.tagName === "SPAN") {
          el.textContent = String(value ?? "");
        }
        break;
      case "value":
        if (el.tagName === "INPUT") el.value = String(value ?? "");
        break;
      case "color":
        el.style.color = String(value);
        break;
      case "backgroundColor":
        el.style.backgroundColor = String(value);
        break;
      case "visible":
        el.style.display = value ? "" : "none";
        break;
      default:
        el.setAttribute("data-bind-" + propName, String(value));
    }
  }

  function readBindingValue(ref) {
    // Web 端初始只能读项目变量默认值
    if (ref.source === "projVar") {
      const v = (PROJECT.projectVars || []).find(v => v.id === ref.varId);
      return v ? v.defaultValue : undefined;
    }
    // 页面函数 outputs：按时间线状态返回（done=缓存值，其他=undefined 加载态占位）。
    if (ref.source === "funcVar" && ref.isPageFunc) {
      const entry = PAGE_FUNC_OUTPUTS.get(ref.funcId);
      if (entry && entry.state === "done" && entry.outputs) {
        return entry.outputs[ref.outputName];
      }
      return undefined; // running/idle/error → 加载态占位（undefined）。
    }
    if (ref.source === "funcVar") return undefined;
    if (ref.source === "upstream") return undefined;
    if (ref.source === "component") return undefined; // 由容器运行时注入，v1 不支持。
    return undefined;
  }

  async function triggerFunction(funcIdOrName) {
    const fn = findFunction(funcIdOrName);
    if (!fn) {
      console.warn("[NodeVisual] Function not found: " + funcIdOrName);
      return;
    }
    const result = await runFunction(fn, {});
    if (result.error) {
      console.error("[NodeVisual] Function error:", result.error);
      return;
    }
    refreshBindings(result.outputs);
  }

  function refreshBindings(outputs) {
    // 简化：遍历 BINDING_REGISTRY，重新读取所有 binding（包含刚执行的输出）
    for (const [id, list] of BINDING_REGISTRY.entries()) {
      for (const b of list) {
        const v = readBindingValueAfterRun(b.ref, outputs);
        if (v !== undefined) applyProp(b.el, b.propName, v);
      }
    }
  }

  function readBindingValueAfterRun(ref, outputs) {
    if (ref.source === "upstream") {
      const k = ref.nodeId + "." + ref.outputName;
      return outputs ? outputs[k] : undefined;
    }
    return readBindingValue(ref);
  }

  // ====== 启动 ======
  async function boot() {
    const errEl = document.getElementById("boot-error");
    try {
      await loadIR();
      document.title = (PROJECT.meta && PROJECT.meta.name) || "NodeVisual App";
      renderUI();
      // 触发所有"应用启动"入口函数（kind=external, ref=app_start）
      if (PROJECT.functions) {
        for (const fn of PROJECT.functions) {
          if (fn.entry && fn.entry.kind === "external" && fn.entry.ref === "app_start") {
            triggerFunction(fn.id);
          }
        }
        // 触发所有页面 onLoad 函数（kind=pageEvent, ref=<pageId>:onLoad）。
        // v1 Web 端按声明序执行所有页面的 onLoad（单页应用按页面切换时
        // 也应触发，但 v1 简化为初始化时一次性触发首个页面）。
        const pages = PROJECT.pages || [];
        const firstPageId = pages.length > 0 ? pages[0].id : null;
        for (const fn of PROJECT.functions) {
          if (!fn.entry || fn.entry.kind !== "pageEvent") continue;
          const ref = fn.entry.ref || "";
          const idx = ref.indexOf(":");
          if (idx <= 0) continue;
          const pageId = ref.substring(0, idx);
          const event = ref.substring(idx + 1);
          if (event !== "onLoad") continue;
          // v1 简化：仅触发首个页面的 onLoad；其他页面的 onLoad 在页面
          // 切换逻辑中触发（待后续实现 SPA 路由时补完）。
          if (firstPageId && pageId === firstPageId) {
            // 异步执行，失败不阻塞其他函数；outputs 缓存到 PAGE_FUNC_OUTPUTS。
            triggerPageFunction(fn);
          }
        }
      }
    } catch (e) {
      console.error("[NodeVisual] Boot failed:", e);
      if (errEl) errEl.textContent = "启动失败: " + e.message;
    }
  }

  // 页面级函数 outputs 缓存（已在文件顶部声明为 PAGE_FUNC_OUTPUTS）。

  async function triggerPageFunction(fn) {
    PAGE_FUNC_OUTPUTS.set(fn.id, { state: "running" });
    try {
      const result = await runFunction(fn, {});
      if (result.error) {
        PAGE_FUNC_OUTPUTS.set(fn.id, { state: "error", error: result.error });
      } else {
        PAGE_FUNC_OUTPUTS.set(fn.id, { state: "done", outputs: result.outputs || {} });
      }
      // 触发引用了此函数 outputs 的 UI 组件重新读取绑定。
      refreshBindingsForPageFunc(fn.id);
    } catch (e) {
      PAGE_FUNC_OUTPUTS.set(fn.id, { state: "error", error: String(e) });
    }
  }

  // 刷新依赖页面函数 outputs 的 UI 绑定（v1 简化：全部刷新）。
  function refreshBindingsForPageFunc(funcId) {
    BINDING_REGISTRY.forEach(entries => {
      for (const e of entries) {
        if (e.ref && e.ref.source === "funcVar" && e.ref.isPageFunc && e.ref.funcId === funcId) {
          const v = readBindingValue(e.ref);
          if (v !== undefined) applyProp(e.el, e.propName, v);
        }
      }
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
''';
  }

  /// 生成 index.html 内容（引用 runtime.js + ir.json + 提供 #app-root 容器）。
  static String indexHtml(String projectName) {
    final safeName = _escapeHtml(projectName);
    return '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>$safeName</title>
  <style>
    * { box-sizing: border-box; }
    html, body { margin: 0; padding: 0; height: 100%; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
    #app-root { min-height: 100vh; padding: 16px; }
    #boot-error { color: #c0392b; padding: 12px; }
    button { padding: 10px 16px; border: none; border-radius: 8px; background: #6200ee; color: white; cursor: pointer; font-size: 14px; }
    input { padding: 8px 12px; border: 1px solid #ccc; border-radius: 8px; font-size: 14px; }
  </style>
</head>
<body>
  <div id="app-root"></div>
  <div id="boot-error"></div>
  <script src="runtime.js"></script>
</body>
</html>
''';
  }

  /// README 内容（说明包结构）。
  static String readmeMd(String projectName) {
    return '''# $projectName - Web 产物

由 NodeVisual App Builder 端侧生成。

## 包结构
- \`index.html\` - 入口页面（任意浏览器打开即可运行）
- \`runtime.js\` - 节点图解释器 + UI 渲染器
- \`ir.json\` - 项目中间表示（IR）
- \`manifest.json\` - 构建清单
- \`README.md\` - 本文件

## 部署
将该目录整体上传到任意静态文件服务器（Nginx / GitHub Pages / Vercel 等），
或直接用浏览器打开 \`index.html\` 即可运行。
''';
  }

  static String _escapeHtml(String s) {
    return s
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
  }
}
