/// Web 运行时模板（JavaScript）。
///
/// 这是嵌入到产物 `runtime.js` 中的 JS 解释器+UI 渲染器，负责：
/// - 加载 `ir.json` 中的项目 IR
/// - 渲染 UI 树为 DOM（Text / Column / Row / Container / Button / Image 等）
/// - 执行节点函数 DAG（控制流遍历 + `#` 引用解析）
/// - 处理 UI 事件触发函数
/// - 函数执行后回写 UI 绑定
///
/// v1 实现常见节点类型的 JS 解释（变量、算术、逻辑、字符串、If、Loop、
/// function_call、return、variable_get/set），其余节点（db_*, plugin_*）
/// 在 Web 端降级为 no-op + console.warn。
class WebRuntimeTemplate {
  WebRuntimeTemplate._();

  /// 生成 runtime.js 内容。
  static String runtimeJs() {
    return '''
// NodeVisual Web Runtime v1
// Auto-generated by NodeVisual App Builder. Interprets IR + renders UI tree.
(function () {
  "use strict";

  // ====== IR 加载 ======
  let IR = null;
  let PROJECT = null;
  const BINDING_REGISTRY = new Map(); // uiNodeId -> { fn: Function, domEl: Element }

  // 页面级函数 outputs 缓存（key = funcId, value = { state, outputs, error }）。
  // 供同页面 UI 组件的 #funcVar 引用按时间线规则读取。声明在此处以保证
  // readBindingValue 可引用（const 不会被运行时函数提升）。
  const PAGE_FUNC_OUTPUTS = new Map();

  async function loadIR() {
    // ir.json 与 runtime.js 同目录
    const resp = await fetch("ir.json", { cache: "no-store" });
    if (!resp.ok) throw new Error("Failed to load ir.json: " + resp.status);
    IR = await resp.json();
    PROJECT = IR;
  }

  // ====== 类型与作用域 ======
  class Scope {
    constructor(parent) {
      this.parent = parent || null;
      this.nodeOutputs = new Map(); // "nodeId.outputName" -> value
      this.funcVars = new Map();
      this.projVars = new Map();
      this.inputs = new Map();
    }
    setOutput(nodeId, name, value) {
      this.nodeOutputs.set(nodeId + "." + name, value);
    }
    getOutput(nodeId, name) {
      const k = nodeId + "." + name;
      if (this.nodeOutputs.has(k)) return this.nodeOutputs.get(k);
      if (this.parent) return this.parent.getOutput(nodeId, name);
      return undefined;
    }
    setFuncVar(id, v) { this.funcVars.set(id, v); }
    getFuncVar(id) {
      if (this.funcVars.has(id)) return this.funcVars.get(id);
      if (this.parent) return this.parent.getFuncVar(id);
      return undefined;
    }
    setProjVar(id, v) { this.projVars.set(id, v); }
    getProjVar(id) {
      if (this.projVars.has(id)) return this.projVars.get(id);
      if (this.parent) return this.parent.getProjVar(id);
      return undefined;
    }
  }

  // 列表组件注册表：uiNodeId -> { el, uiNode }。
  // 当页面函数 outputs 就绪后，重新渲染依赖该 outputs 的列表组件。
  const LIST_REGISTRY = new Map();

  // ====== # 引用解析 ======
  //
  // 支持两种 JSON 形式：
  // 1. 裸 VariableRef JSON（节点 params 中的 # 引用）：`{source, nodeId, ...}`
  //    由节点编辑页 _commitParam 调用 r.toJson() 写入，与 Dart 端
  //    node_executors.resolveRef 的 `value.containsKey('source')` 分支对齐。
  // 2. Binding 包装形式（UI 绑定）：`{ref: {source, nodeId, ...}}`
  //    由 UI 编辑器写入属性 binding 字段。
  function resolveRef(value, scope) {
    if (value && typeof value === "object") {
      let r;
      if (value.ref) {
        r = value.ref;
      } else if (value.source) {
        r = value;
      } else {
        return value;
      }
      if (r.source === "upstream") {
        return scope.getOutput(r.nodeId, r.outputName);
      } else if (r.source === "funcVar") {
        // 页面级函数 outputs：按状态机返回（仅在 done 时返回缓存值）。
        if (r.funcId && r.outputName) {
          const entry = scope.getPageFuncEntry && scope.getPageFuncEntry(r.funcId);
          if (!entry || entry.state !== "done") return undefined;
          return entry.outputs[r.outputName];
        }
        return scope.getFuncVar(r.varId);
      } else if (r.source === "projVar") {
        return scope.getProjVar(r.varId);
      } else if (r.source === "component") {
        if (!r.componentId || !r.fieldName) return undefined;
        const ctx = findComponentContext(r.componentId);
        return ctx ? ctx.fields.get(r.fieldName) : undefined;
      } else if (r.source === "device") {
        return resolveDeviceProperty(r.property);
      }
    }
    return value;
  }

  // 设备变量属性解析（与 Dart 端 _resolveDeviceProperty 对齐）。
  function resolveDeviceProperty(property) {
    switch (property) {
      case "timezone": {
        // 浏览器 Intl.DateTimeFormat 给出 IANA 时区名（如 "Asia/Shanghai"）。
        try {
          return Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
        } catch (_) {
          return "UTC";
        }
      }
      case "time":
        return new Date().toISOString();
      case "deviceType":
      default:
        // Web 端始终为 "web"。
        return "web";
    }
  }

  // 组件上下文栈（运行时按组件树位置注入）。
  // 每项 = { componentId, fields: Map<String, any> }。
  // list_vertical/horizontal 注入 {item, index}；slider/switch 注入 {value}；
  // tab_container 注入 {tab}。子组件通过 #component 引用读取。
  const COMPONENT_CONTEXT_STACK = [];

  function pushComponentContext(ctx) { COMPONENT_CONTEXT_STACK.push(ctx); }
  function popComponentContext() { COMPONENT_CONTEXT_STACK.pop(); }
  function findComponentContext(componentId) {
    for (let i = COMPONENT_CONTEXT_STACK.length - 1; i >= 0; i--) {
      const c = COMPONENT_CONTEXT_STACK[i];
      if (c.componentId === componentId) return c;
    }
    return null;
  }

  // ====== 节点执行 ======
  function findFunction(funcIdOrName) {
    if (!PROJECT || !PROJECT.functions) return null;
    return PROJECT.functions.find(f => f.id === funcIdOrName || f.name === funcIdOrName);
  }

  function findEntryNode(func) {
    if (!func || !func.nodes) return null;
    const inDeg = new Map();
    func.nodes.forEach(n => inDeg.set(n.id, 0));
    (func.controlEdges || []).forEach(e => {
      if (inDeg.has(e.toNode)) inDeg.set(e.toNode, inDeg.get(e.toNode) + 1);
    });
    // 取无入边中第一个
    for (const n of func.nodes) {
      if (inDeg.get(n.id) === 0) return n;
    }
    return func.nodes[0] || null;
  }

  function findNextNode(func, currentId, controlOutputName) {
    if (!func.controlEdges) return null;
    // 取匹配 fromNode + fromPort 的第一条未访问边
    const edges = func.controlEdges.filter(e =>
      e.fromNode === currentId && (e.fromPort === controlOutputName || !controlOutputName)
    );
    if (edges.length === 0) return null;
    return edges[0].toNode;
  }

  const MAX_STEPS = 10000;

  async function runFunction(func, inputs) {
    const scope = new Scope();
    inputs = inputs || {};
    // 项目变量默认值
    (PROJECT.projectVars || []).forEach(v => scope.setProjVar(v.id, v.defaultValue));
    // 函数变量入参
    Object.keys(inputs).forEach(k => {
      const fv = (func.funcVars || []).find(v => v.name === k);
      if (fv) scope.setFuncVar(fv.id, inputs[k]);
    });
    (func.funcVars || []).forEach(v => {
      if (!inputs[v.name]) scope.setFuncVar(v.id, v.defaultValue);
    });

    let node = findEntryNode(func);
    let steps = 0;
    let lastControlOut = null;
    while (node && steps < MAX_STEPS) {
      steps++;
      const result = await executeNode(node, func, scope);
      if (result.error) return { error: result.error };
      if (result.return !== undefined) {
        // 多返回值（map）：按 outputs 名直接返回，供调用方按名读取。
        if (result.return !== null && typeof result.return === "object" && !Array.isArray(result.return)) {
          return { outputs: result.return };
        }
        // 单返回值（向后兼容）：封装为 { value: v }。
        return { outputs: { value: result.return } };
      }
      // 记录节点所有 dataOutputs 到 scope
      if (node.dataOutputs) {
        for (const out of node.dataOutputs) {
          if (result.outputs && result.outputs[out.name] !== undefined) {
            scope.setOutput(node.id, out.name, result.outputs[out.name]);
          }
        }
      }
      lastControlOut = result.controlOutput || null;
      const nextId = findNextNode(func, node.id, lastControlOut);
      if (!nextId) break;
      node = func.nodes.find(n => n.id === nextId);
    }
    return { outputs: collectOutputs(scope) };
  }

  function collectOutputs(scope) {
    // 取所有 nodeOutputs 作为返回值
    const out = {};
    for (const [k, v] of scope.nodeOutputs.entries()) {
      out[k] = v;
    }
    return out;
  }

  async function executeNode(node, func, scope) {
    const params = node.params || {};
    switch (node.kind) {
      case "variable_set": {
        const v = resolveRef(params.value, scope);
        const target = params.target || "funcVar";
        const varId = params.varId;
        if (!varId) return { controlOutput: "next" };
        if (target === "projVar") {
          scope.setProjVar(varId, v);
        } else {
          // funcVar：仅当 varId 属于当前函数 funcVars 时才设置（防越权）。
          const exists = (func.funcVars || []).some(v => v.id === varId);
          if (exists) scope.setFuncVar(varId, v);
        }
        // 与 Dart 端 _execVariableSet 对齐：variable_set 无 dataOutputs，
        // 仅走控制流 next 输出（不返回 value，避免误用）。
        return { controlOutput: "next" };
      }
      case "variable_get": {
        // 兼容旧 IR；新项目应通过 # 引用读取。
        const v = scope.getFuncVar(params.varId || params.varName);
        return { outputs: { value: v } };
      }
      case "arithmetic": {
        const a = resolveRef(params.a, scope);
        const b = resolveRef(params.b, scope);
        const op = params.op || "+";
        let r;
        switch (op) {
          case "+": r = (a || 0) + (b || 0); break;
          case "-": r = (a || 0) - (b || 0); break;
          case "*": r = (a || 0) * (b || 0); break;
          case "/": r = (b || 0) === 0 ? null : (a || 0) / (b || 0); break;
          case "%": r = (b || 0) === 0 ? null : (a || 0) % (b || 0); break;
          default: r = null;
        }
        return { outputs: { result: r } };
      }
      case "logic": {
        const a = resolveRef(params.a, scope);
        const b = resolveRef(params.b, scope);
        const op = params.op || "&&";
        let r;
        switch (op) {
          case "&&": r = !!a && !!b; break;
          case "||": r = !!a || !!b; break;
          case "!": r = !a; break;
          case "==": r = a === b; break;
          case "!=": r = a !== b; break;
          case ">": r = a > b; break;
          case "<": r = a < b; break;
          case ">=": r = a >= b; break;
          case "<=": r = a <= b; break;
          default: r = false;
        }
        return { outputs: { result: r } };
      }
      case "string_op": {
        const a = String(resolveRef(params.a, scope) ?? "");
        const b = String(resolveRef(params.b, scope) ?? "");
        const op = params.op || "concat";
        let r;
        switch (op) {
          case "concat": r = a + b; break;
          case "upper": r = a.toUpperCase(); break;
          case "lower": r = a.toLowerCase(); break;
          case "substring": {
            const start = Number(resolveRef(params.start, scope) || 0);
            const end = Number(resolveRef(params.end, scope) || a.length);
            r = a.substring(start, end); break;
          }
          case "length": r = a.length; break;
          case "contains": r = a.includes(b); break;
          case "replace": r = a.split(b).join(String(resolveRef(params.replacement, scope) || "")); break;
          default: r = a;
        }
        return { outputs: { result: r } };
      }
      case "if": {
        const cond = resolveRef(params.condition, scope);
        const cases = params.cases || [];
        for (const c of cases) {
          const cv = resolveRef(c.value, scope);
          // case value 为 null 表示 default/else
          if (c.value === null || c.value === undefined || cv === cond) {
            return { controlOutput: c.label || "true", outputs: {} };
          }
        }
        return { controlOutput: cond ? "true" : "false", outputs: {} };
      }
      case "loop": {
        // v1: 简化为 for-each over list
        const list = resolveRef(params.list, scope) || [];
        const bodyPort = "body";
        const completedPort = "completed";
        // 简化：直接展开循环（不真执行子图，仅登记 item/index）
        let idx = 0;
        for (const item of list) {
          scope.setOutput(node.id, "item", item);
          scope.setOutput(node.id, "index", idx++);
        }
        return { controlOutput: completedPort, outputs: { count: idx } };
      }
      case "function_call": {
        const targetFn = findFunction(params.functionId || params.functionName);
        if (!targetFn) return { error: "Function not found: " + (params.functionId || params.functionName) };
        const callInputs = {};
        Object.keys(params.inputs || {}).forEach(k => {
          callInputs[k] = resolveRef(params.inputs[k], scope);
        });
        const r = await runFunction(targetFn, callInputs);
        if (r.error) return { error: r.error };
        return { outputs: { result: r.outputs } };
      }
      case "return": {
        // 多返回值（新格式）：values 为 map<name, ref>，按函数 outputs 名映射。
        if (params.values && typeof params.values === "object") {
          const out = {};
          Object.keys(params.values).forEach(k => {
            out[k] = resolveRef(params.values[k], scope);
          });
          return { return: out };
        }
        // 单返回值（向后兼容）：value 字段。
        const v = resolveRef(params.value, scope);
        return { return: v };
      }
      case "literal": {
        return { outputs: { value: params.value } };
      }
      case "code_run": {
        // 在 Web 端直接用浏览器 JS 引擎 eval 用户代码。
        // 注入 inputs 全局变量；最后一行表达式的求值结果作为 result。
        const lang = params.language || "javascript";
        if (lang !== "javascript") {
          throw new Error("code_run 仅支持 javascript，得到：" + lang);
        }
        const code = params.code || "";
        if (!code || !code.trim()) {
          return { outputs: { result: null } };
        }
        // 解析 inputs（Map 或 JSON 字符串）。
        let inputsVal = resolveRef(params.inputs, scope);
        let inputsMap = {};
        if (inputsVal && typeof inputsVal === "object" && !Array.isArray(inputsVal)) {
          inputsMap = inputsVal;
        } else if (typeof inputsVal === "string" && inputsVal.trim()) {
          try {
            const d = JSON.parse(inputsVal);
            if (d && typeof d === "object" && !Array.isArray(d)) inputsMap = d;
          } catch (e) { /* 降级为空 */ }
        }
        try {
          // eslint-disable-next-line no-new-func
          const fn = new Function("inputs", "\"use strict\";\n" + code);
          const result = fn(inputsMap);
          return { outputs: { result: result === undefined ? null : result } };
        } catch (e) {
          throw new Error("code_run 执行失败：" + e.message);
        }
      }
      default:
        if (node.kind && node.kind.indexOf("db_") === 0) {
          console.warn("[NodeVisual] DB node not supported in Web runtime: " + node.kind);
          return { outputs: {} };
        }
        if (node.kind && node.kind.indexOf("plugin_") === 0) {
          console.warn("[NodeVisual] Plugin node not supported in Web runtime: " + node.kind);
          return { outputs: {} };
        }
        console.warn("[NodeVisual] Unknown node kind: " + node.kind);
        return { outputs: {} };
    }
  }

  // ====== 布局与样式（9宫格堆叠 + 绝对布局 + 样式应用）======
  //
  // 以下函数将 UiNode.layout (LayoutConfig) / UiNode.style 映射到 CSS，
  // 并实现与 Dart 端 RelativeLayoutEngine / AbsoluteLayoutRenderObject 等价的
  // 9 宫格堆叠算法（cell 1-9 分组 + distance 排序 + 方向堆叠）。

  // SizeSpec → CSS 像素字符串（百分比相对 parentExtent；应用 minPx/maxPx）。
  function resolveSize(spec, parentExtent) {
    if (!spec) return "";
    if (spec.unit === "percent") {
      var v = (parentExtent || 0) * (spec.value / 100);
      if (spec.minPx != null) v = Math.max(v, spec.minPx);
      if (spec.maxPx != null) v = Math.min(v, spec.maxPx);
      return v + "px";
    }
    return spec.value + "px";
  }

  // EdgeValue → CSS 像素字符串。
  function resolveEdge(edge, parentExtent) {
    if (!edge) return "0px";
    if (edge.unit === "percent") {
      return ((parentExtent || 0) * (edge.value / 100)) + "px";
    }
    return edge.value + "px";
  }

  // PositionSpec → 像素数值（绝对布局用）。
  function resolvePosition(spec, parentExtent) {
    if (!spec) return 0;
    if (spec.unit === "percent") {
      return (parentExtent || 0) * (spec.value / 100);
    }
    return spec.value;
  }

  // 应用 LayoutConfig 到元素本身（width/height/margin）。
  // 位置（cell/distance/x/y）由父容器的堆叠算法计算，此处不设置。
  // parentEl 用于解析 percent 单位（宽度/高度相对父容器）；未提供时
  // percent 退化为 0（由调用方在挂载后覆盖设置）。
  function applyLayout(el, uiNode, parentEl) {
    var layout = uiNode.layout;
    if (!layout) return;
    var pw = (parentEl && parentEl.clientWidth) ? parentEl.clientWidth : 0;
    var ph = (parentEl && parentEl.clientHeight) ? parentEl.clientHeight : 0;
    if (layout.width) el.style.width = resolveSize(layout.width, pw);
    if (layout.height) el.style.height = resolveSize(layout.height, ph);
    if (layout.margin) {
      el.style.marginTop = resolveEdge(layout.margin.top, ph);
      el.style.marginBottom = resolveEdge(layout.margin.bottom, ph);
      el.style.marginLeft = resolveEdge(layout.margin.left, pw);
      el.style.marginRight = resolveEdge(layout.margin.right, pw);
    }
  }

  // 应用 UiNode.style（视觉样式 map）到元素。
  // 识别常见样式键：color / backgroundColor / fontSize / fontWeight /
  // padding / borderRadius / border / opacity / visibility。
  function applyStyle(el, uiNode) {
    var style = uiNode.style;
    if (!style) return;
    Object.keys(style).forEach(function(k) {
      var v = style[k];
      if (v == null) return;
      switch (k) {
        case "color": el.style.color = String(v); break;
        case "backgroundColor": el.style.backgroundColor = String(v); break;
        case "fontSize":
          el.style.fontSize = (typeof v === "number") ? v + "px" : String(v); break;
        case "fontWeight": el.style.fontWeight = String(v); break;
        case "fontFamily": el.style.fontFamily = String(v); break;
        case "padding": el.style.padding = (typeof v === "number") ? v + "px" : String(v); break;
        case "paddingTop": el.style.paddingTop = (typeof v === "number") ? v + "px" : String(v); break;
        case "paddingBottom": el.style.paddingBottom = (typeof v === "number") ? v + "px" : String(v); break;
        case "paddingLeft": el.style.paddingLeft = (typeof v === "number") ? v + "px" : String(v); break;
        case "paddingRight": el.style.paddingRight = (typeof v === "number") ? v + "px" : String(v); break;
        case "margin": el.style.margin = (typeof v === "number") ? v + "px" : String(v); break;
        case "borderRadius": el.style.borderRadius = (typeof v === "number") ? v + "px" : String(v); break;
        case "border": el.style.border = String(v); break;
        case "borderWidth": el.style.borderWidth = (typeof v === "number") ? v + "px" : String(v); break;
        case "borderColor": el.style.borderColor = String(v); break;
        case "borderStyle": el.style.borderStyle = String(v); break;
        case "opacity": el.style.opacity = String(v); break;
        case "visibility": el.style.visibility = String(v); break;
        case "overflow": el.style.overflow = String(v); break;
        case "boxShadow": el.style.boxShadow = String(v); break;
        case "textAlign": el.style.textAlign = String(v); break;
        case "letterSpacing": el.style.letterSpacing = (typeof v === "number") ? v + "px" : String(v); break;
        case "lineHeight": el.style.lineHeight = String(v); break;
        case "minWidth": el.style.minWidth = (typeof v === "number") ? v + "px" : String(v); break;
        case "maxWidth": el.style.maxWidth = (typeof v === "number") ? v + "px" : String(v); break;
        case "minHeight": el.style.minHeight = (typeof v === "number") ? v + "px" : String(v); break;
        case "maxHeight": el.style.maxHeight = (typeof v === "number") ? v + "px" : String(v); break;
        default:
          // 未知样式键直接写入（CSS 自定义属性或已知 CSS 属性）。
          el.style.setProperty(k, String(v));
      }
    });
  }

  // 返回某 cell（1-9）的堆叠信息：flexDirection + 水平/垂直对齐。
  // 与 Dart 端 RelativeLayoutRenderObject._positionCell 对齐：
  // - cell 1/2/3: 从顶部往下堆叠（flex-direction: column）
  // - cell 7/8/9: 从底部往上堆叠（flex-direction: column-reverse）
  // - cell 4: 从左往右堆叠（flex-direction: row）
  // - cell 6: 从右往左堆叠（flex-direction: row-reverse）
  // - cell 5: 中心，默认从上往下堆叠（distance.edge=top 时反向）
  function getCellStackingInfo(cell) {
    switch (cell) {
      case 1: return { flexDirection: "column",  justifyContent: "flex-start", alignItems: "flex-start" };
      case 2: return { flexDirection: "column",  justifyContent: "flex-start", alignItems: "center" };
      case 3: return { flexDirection: "column",  justifyContent: "flex-start", alignItems: "flex-end" };
      case 4: return { flexDirection: "row",     justifyContent: "flex-start", alignItems: "center" };
      case 5: return { flexDirection: "column",  justifyContent: "center",   alignItems: "center" };
      case 6: return { flexDirection: "row-reverse", justifyContent: "flex-start", alignItems: "center" };
      case 7: return { flexDirection: "column-reverse", justifyContent: "flex-start", alignItems: "flex-start" };
      case 8: return { flexDirection: "column-reverse", justifyContent: "flex-start", alignItems: "center" };
      case 9: return { flexDirection: "column-reverse", justifyContent: "flex-start", alignItems: "flex-end" };
      default: return { flexDirection: "column", justifyContent: "center", alignItems: "center" };
    }
  }

  // 渲染 9 宫格堆叠布局：父容器 flex column，每个 cell 容器 width 100%
  // 撑满父容器，cell 内按堆叠方向（flexDirection）排列子组件。
  // 子组件的 width 100% 相对父容器解析，实现左右撑满。
  // 相对布局无"距边距离"概念，cell 决定对齐（列）与排列方向（行）。
  function renderChildrenRelative(parentEl, children) {
    parentEl.style.position = "relative";
    parentEl.style.display = "flex";
    parentEl.style.flexDirection = "column";
    parentEl.style.width = "100%";

    // 按 cell 分组（默认 cell=2 上中，与 Dart 端 defaultCell 一致）。
    var groups = {};
    children.forEach(function(child) {
      var cell = (child.layout && child.layout.cell) ? child.layout.cell.cell : 2;
      if (!groups[cell]) groups[cell] = [];
      groups[cell].push(child);
    });

    var pw = parentEl.clientWidth || parentEl.offsetWidth || 0;
    var ph = parentEl.clientHeight || parentEl.offsetHeight || 0;

    // 按 cell 1→9 顺序渲染，每个 cell 容器 width 100% 撑满父容器。
    var cellOrder = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    cellOrder.forEach(function(cell) {
      var cellChildren = groups[cell];
      if (!cellChildren || cellChildren.length === 0) return;

      var info = getCellStackingInfo(cell);
      var cellEl = document.createElement("div");
      cellEl.style.display = "flex";
      cellEl.style.flexDirection = info.flexDirection;
      cellEl.style.justifyContent = info.justifyContent;
      cellEl.style.alignItems = info.alignItems;
      cellEl.style.width = "100%";
      cellEl.style.minHeight = "0";
      cellEl.style.minWidth = "0";

      cellChildren.forEach(function(child) {
        var childEl = renderNode(child, cellEl);
        if (childEl) {
          // 覆盖设置 width/height/margin（基于父容器尺寸解析 percent），
          // 确保 width 100% 撑满父容器。
          var layout = child.layout;
          if (layout) {
            if (layout.width) childEl.style.width = resolveSize(layout.width, pw);
            if (layout.height) childEl.style.height = resolveSize(layout.height, ph);
            if (layout.margin) {
              childEl.style.marginTop = resolveEdge(layout.margin.top, ph);
              childEl.style.marginBottom = resolveEdge(layout.margin.bottom, ph);
              childEl.style.marginLeft = resolveEdge(layout.margin.left, pw);
              childEl.style.marginRight = resolveEdge(layout.margin.right, pw);
            }
          }
          cellEl.appendChild(childEl);
        }
      });
      parentEl.appendChild(cellEl);
    });
  }

  // 渲染绝对布局：父容器 position:relative，子组件 position:absolute。
  function renderChildrenAbsolute(parentEl, children) {
    parentEl.style.position = "relative";
    parentEl.style.display = "block";
    children.forEach(function(child) {
      var childEl = renderNode(child, parentEl);
      if (!childEl) return;
      var layout = child.layout;
      if (layout && layout.mode === "absolute") {
        childEl.style.position = "absolute";
        if (layout.x) childEl.style.left = resolvePosition(layout.x, parentEl.clientWidth) + "px";
        if (layout.y) childEl.style.top = resolvePosition(layout.y, parentEl.clientHeight) + "px";
        if (layout.width) childEl.style.width = resolveSize(layout.width, parentEl.clientWidth);
        if (layout.height) childEl.style.height = resolveSize(layout.height, parentEl.clientHeight);
        if (layout.margin) {
          childEl.style.marginTop = resolveEdge(layout.margin.top, parentEl.clientHeight);
          childEl.style.marginBottom = resolveEdge(layout.margin.bottom, parentEl.clientHeight);
          childEl.style.marginLeft = resolveEdge(layout.margin.left, parentEl.clientWidth);
          childEl.style.marginRight = resolveEdge(layout.margin.right, parentEl.clientWidth);
        }
      }
      parentEl.appendChild(childEl);
    });
  }

  // 检测子组件列表是否含有 LayoutConfig（决定布局模式）。
  function childrenHaveLayout(children) {
    return (children || []).some(function(c) { return c && c.layout; });
  }

  // 检测子组件列表中是否含绝对布局节点。
  function childrenHaveAbsolute(children) {
    return (children || []).some(function(c) {
      return c && c.layout && c.layout.mode === "absolute";
    });
  }

  // ====== 动画系统（入场 / 触发动画）======
  //
  // 将 AnimationSpec 映射为 CSS 动画：
  // - 预设动画（preset）：fade/slide/scale/bounce/rotate/elastic → CSS @keyframes
  // - 关键帧动画（keyframes）：动态生成 @keyframes 注入 <style>
  // - 缓动（easing）：映射到 CSS transition-timing-function / animation-timing-function

  // EasingType → CSS easing 函数。
  function easingToCss(easing) {
    switch (easing) {
      case "linear": return "linear";
      case "easeIn": return "cubic-bezier(0.42, 0, 1, 1)";
      case "easeOut": return "cubic-bezier(0, 0, 0.58, 1)";
      case "easeInOut": return "cubic-bezier(0.42, 0, 0.58, 1)";
      case "bounce": return "cubic-bezier(0.68, -0.55, 0.265, 1.55)";
      case "elastic": return "cubic-bezier(0.5, -0.5, 0.1, 1.5)";
      default: return "ease";
    }
  }

  // 预设动画 → CSS @keyframes 定义字符串。
  // params 可包含 direction（slide 方向：left/right/up/down）。
  function presetToKeyframes(preset, params) {
    var p = params || {};
    switch (preset) {
      case "fade":
        return "@keyframes nv-fade { from { opacity: 0; } to { opacity: 1; } }";
      case "slide": {
        var dir = p.direction || "up";
        var from = "translate(0, 0)";
        switch (dir) {
          case "left":  from = "translateX(-100%)"; break;
          case "right": from = "translateX(100%)"; break;
          case "up":    from = "translateY(100%)"; break;
          case "down":  from = "translateY(-100%)"; break;
        }
        return "@keyframes nv-slide { from { transform: " + from + "; } to { transform: translate(0, 0); } }";
      }
      case "scale":
        return "@keyframes nv-scale { from { transform: scale(0); } to { transform: scale(1); } }";
      case "bounce":
        return "@keyframes nv-bounce { 0% { transform: scale(0.3); opacity: 0; } 50% { transform: scale(1.1); opacity: 1; } 70% { transform: scale(0.9); } 100% { transform: scale(1); } }";
      case "rotate":
        return "@keyframes nv-rotate { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }";
      case "elastic":
        return "@keyframes nv-elastic { 0% { transform: scale(0); } 55% { transform: scale(1.15); } 75% { transform: scale(0.95); } 100% { transform: scale(1); } }";
      default:
        return "@keyframes nv-fade { from { opacity: 0; } to { opacity: 1; } }";
    }
  }

  // 动画 keyframe 序号计数器（保证每次生成唯一 @keyframes 名）。
  var _animSeq = 0;

  // 关键帧动画 → 动态生成 @keyframes 注入 <style>，返回动画名。
  function buildKeyframeAnimation(keyframes) {
    if (!keyframes || keyframes.length === 0) return null;
    var name = "nv-kf-" + (++_animSeq);
    var css = "@keyframes " + name + " {";
    // 按 time 升序排序（0-1 归一化时间）。
    var sorted = keyframes.slice().sort(function(a, b) { return a.time - b.time; });
    sorted.forEach(function(kf) {
      var pct = Math.max(0, Math.min(100, kf.time * 100));
      css += pct + "% {";
      var props = kf.properties || {};
      if (props.x != null || props.y != null) {
        css += " transform: translate(" + (props.x || 0) + "px, " + (props.y || 0) + "px);";
      }
      if (props.opacity != null) css += " opacity: " + props.opacity + ";";
      if (props.scale != null) css += " transform: scale(" + props.scale + ");";
      if (props.rotation != null) css += " transform: rotate(" + props.rotation + "deg);";
      css += " }";
    });
    css += " }";
    // 注入 <style>。
    var style = document.createElement("style");
    style.type = "text/css";
    style.textContent = css;
    document.head.appendChild(style);
    return name;
  }

  // 播放一个 AnimationSpec：
  // - 预设动画：注入对应 @keyframes 并应用 animation。
  // - 关键帧动画：动态生成 @keyframes 并应用 animation。
  // onComplete 在动画结束时回调（用于出场动画后移除元素）。
  function playAnimation(el, spec, onComplete) {
    if (!spec) return;
    var name = null;
    if (spec.preset) {
      // 预设动画：注入 @keyframes（若未注入过）。
      var styleId = "nv-anim-style-" + spec.preset;
      if (!document.getElementById(styleId)) {
        var style = document.createElement("style");
        style.id = styleId;
        style.type = "text/css";
        style.textContent = presetToKeyframes(spec.preset, spec.params);
        document.head.appendChild(style);
      }
      name = "nv-" + spec.preset;
    } else if (spec.keyframes && spec.keyframes.length > 0) {
      name = buildKeyframeAnimation(spec.keyframes);
    }
    if (!name) return;
    var duration = (spec.duration || 300);
    var delay = (spec.delay || 0);
    var easing = easingToCss(spec.easing);
    el.style.animation = name + " " + duration + "ms " + easing + " " + delay + "ms 1 normal both";
    if (onComplete) {
      var called = false;
      var handler = function() {
        if (called) return;
        called = true;
        el.removeEventListener("animationend", handler);
        onComplete();
      };
      el.addEventListener("animationend", handler);
      // 兜底：超时后强制回调（防止 animationend 不触发）。
      setTimeout(handler, duration + delay + 50);
    }
  }

  // 入场动画：组件首次渲染时播放。
  function applyEntranceAnimation(el, uiNode) {
    var anims = uiNode.animations;
    if (!anims || !anims.entrance) return;
    // 延迟到下一帧播放，确保元素已挂载到 DOM。
    requestAnimationFrame(function() {
      playAnimation(el, anims.entrance);
    });
  }

  // 触发动画：将 uiNode.animations.triggered 列表绑定到对应事件。
  // 事件名 → DOM 事件映射：onTap→click, onPress→mousedown, onLongPress→contextmenu 等。
  function applyTriggeredAnimations(el, uiNode) {
    var anims = uiNode.animations;
    if (!anims || !anims.triggered || anims.triggered.length === 0) return;
    anims.triggered.forEach(function(t) {
      var domEvt = triggerEventToDom(t.event);
      if (!domEvt) return;
      el.addEventListener(domEvt, function() {
        playAnimation(el, t.animation);
      });
    });
  }

  // UI 事件名 → DOM 事件名映射。
  function triggerEventToDom(eventName) {
    switch (eventName) {
      case "onTap": return "click";
      case "onPress": return "mousedown";
      case "onLongPress": return "contextmenu";
      case "onDoubleTap": return "dblclick";
      case "onHover": return "mouseenter";
      case "onFocus": return "focus";
      case "onBlur": return "blur";
      case "onChange": return "change";
      case "onSubmit": return "submit";
      default: return null;
    }
  }

  // ====== UI 渲染 ======
  function renderUI() {
    if (!PROJECT || !PROJECT.ui) return;
    var root = document.getElementById("app-root");
    if (!root) return;
    root.innerHTML = "";
    // PROJECT.ui 为 Page 节点数组（type='page'）。每个 Page 节点的 children
    // 为该页面的 UI 根节点树。v1 渲染首页（isHome=true）或首个 Page。
    // 后续页面切换由 SPA 路由处理（待实现）。
    var pages = Array.isArray(PROJECT.ui)
      ? PROJECT.ui.filter(function(n) { return n && n.type === "page"; })
      : [];
    if (pages.length === 0) return;
    var pageNode = pages.find(function(p) { return p.props && p.props.isHome === true; });
    if (!pageNode) pageNode = pages[0];

    // Page 节点本身作为根容器：应用 Page 的 layout（默认 100%×100%）与
    // 页面级样式（background 等）。
    var pageStyle = pageNode.props || {};
    root.style.minHeight = "100vh";
    if (pageStyle.background) root.style.background = String(pageStyle.background);
    // safeArea：Web 端通过 padding 模拟（v1 简化）。
    var padTop = (pageStyle.safeAreaTop !== false) ? "env(safe-area-inset-top)" : "0";
    var padBottom = (pageStyle.safeAreaBottom !== false) ? "env(safe-area-inset-bottom)" : "0";
    root.style.paddingTop = padTop;
    root.style.paddingBottom = padBottom;

    // 渲染 Page 节点的 children 作为 UI 根树。
    // 布局强制开启：含 LayoutConfig 时按 9 宫格堆叠或绝对坐标定位；
    // 历史数据无 layout 时回退到默认垂直堆叠。
    var pageChildren = pageNode.children || [];
    if (childrenHaveAbsolute(pageChildren)) {
      renderChildrenAbsolute(root, pageChildren);
    } else if (childrenHaveLayout(pageChildren)) {
      renderChildrenRelative(root, pageChildren);
    } else {
      pageChildren.forEach(function(child) {
        var el = renderNode(child, null);
        if (el) root.appendChild(el);
      });
    }

    // 触发 Page 节点的 onLoad 事件（triggers.onLoad）。
    // 使用 triggerPageFunction 而非 triggerFunction，以便 outputs 缓存到
    // PAGE_FUNC_OUTPUTS 供同页面 UI 组件的 #funcVar 引用按时间线规则解析。
    if (pageNode.triggers && pageNode.triggers.onLoad) {
      var onLoadFn = findFunction(pageNode.triggers.onLoad);
      if (onLoadFn) {
        setTimeout(function() { triggerPageFunction(onLoadFn); }, 0);
      } else {
        // 函数未找到时降级为按 id/name 触发（可能仅记录日志）。
        setTimeout(function() { triggerFunction(pageNode.triggers.onLoad); }, 0);
      }
    }
  }

  function renderNode(uiNode, parent) {
    if (!uiNode || !uiNode.type) return null;
    let el;
    switch (uiNode.type) {
      case "Column":
        el = document.createElement("div");
        el.style.display = "flex";
        el.style.flexDirection = "column";
        el.style.gap = (uiNode.props.gap || 8) + "px";
        break;
      case "Row":
        el = document.createElement("div");
        el.style.display = "flex";
        el.style.flexDirection = "row";
        el.style.gap = (uiNode.props.gap || 8) + "px";
        break;
      case "Container":
      case "card":
        el = document.createElement("div");
        if (uiNode.type === "card") {
          el.style.border = "1px solid #e0e0e0";
          el.style.borderRadius = "8px";
          el.style.padding = "12px";
          el.style.boxShadow = "0 1px 3px rgba(0,0,0,0.08)";
        }
        if (uiNode.props.padding) el.style.padding = uiNode.props.padding + "px";
        if (uiNode.props.color) el.style.backgroundColor = uiNode.props.color;
        if (uiNode.props.width) el.style.width = uiNode.props.width + "px";
        if (uiNode.props.height) el.style.height = uiNode.props.height + "px";
        break;
      case "Text":
        el = document.createElement("span");
        el.textContent = String(uiNode.props.text || "");
        if (uiNode.props.fontSize) el.style.fontSize = uiNode.props.fontSize + "px";
        if (uiNode.props.color) el.style.color = uiNode.props.color;
        if (uiNode.props.fontWeight) el.style.fontWeight = uiNode.props.fontWeight;
        break;
      case "rich_text":
        el = document.createElement("div");
        el.innerHTML = String(uiNode.props.text || "");
        break;
      case "ElevatedButton":
      case "button":
        el = document.createElement("button");
        el.textContent = String(uiNode.props.label || "Button");
        // 事件触发：从 uiNode.triggers.onTap 读取函数 id（新结构），
        // 向后兼容旧 props.onTap（旧 IR）。
        var onTapFn = (uiNode.triggers && uiNode.triggers.onTap) || uiNode.props.onTap;
        if (onTapFn) {
          el.addEventListener("click", function() { triggerFunction(onTapFn); });
        }
        break;
      case "TextField":
      case "text_field":
        el = document.createElement("input");
        el.type = "text";
        el.placeholder = String(uiNode.props.placeholder || "");
        break;
      case "Image":
        el = document.createElement("img");
        if (uiNode.props.src) el.src = uiNode.props.src;
        el.alt = String(uiNode.props.alt || "");
        break;
      case "video":
        el = document.createElement("video");
        if (uiNode.props.src) el.src = uiNode.props.src;
        el.controls = true;
        break;
      case "Scaffold":
        el = document.createElement("div");
        break;
      case "slider": {
        el = document.createElement("input");
        el.type = "range";
        const sMin = Number(uiNode.props.min ?? 0);
        const sMax = Number(uiNode.props.max ?? 100);
        const sVal = Number(uiNode.props.value ?? sMin);
        el.min = sMin;
        el.max = sMax;
        el.value = sVal;
        // 滑块当前值作为组件上下文提供给子节点 #value 引用。
        el._componentContext = { componentId: uiNode.id, fields: { value: sVal } };
        // onChanged 触发：优先从 uiNode.triggers 读取（新结构），
        // 向后兼容 uiNode.props.onChanged（旧 IR）。
        var onChangedFn = (uiNode.triggers && uiNode.triggers.onChanged) || uiNode.props.onChanged;
        if (onChangedFn) {
          el.addEventListener("input", function() {
            const v = Number(el.value);
            if (el._componentContext) el._componentContext.fields.value = v;
            triggerFunction(onChangedFn);
          });
        }
        break;
      }
      case "switch":
        el = document.createElement("input");
        el.type = "checkbox";
        el.checked = !!uiNode.props.value;
        el._componentContext = { componentId: uiNode.id, fields: { value: !!uiNode.props.value } };
        break;
      case "checkbox":
        el = document.createElement("input");
        el.type = "checkbox";
        el.checked = !!uiNode.props.value;
        break;
      case "progress": {
        el = document.createElement("div");
        el.style.height = "4px";
        el.style.background = "#e0e0e0";
        el.style.borderRadius = "2px";
        const inner = document.createElement("div");
        inner.style.height = "100%";
        inner.style.background = "#6200ee";
        inner.style.width = (Number(uiNode.props.value ?? 0) * 100) + "%";
        el.appendChild(inner);
        break;
      }
      case "badge":
        el = document.createElement("span");
        el.style.background = "#6200ee";
        el.style.color = "white";
        el.style.padding = "2px 8px";
        el.style.borderRadius = "10px";
        el.style.fontSize = "11px";
        el.textContent = String(uiNode.props.text || "");
        break;
      case "divider":
        el = document.createElement("hr");
        break;
      case "spacer":
        el = document.createElement("div");
        if (uiNode.props.width) el.style.width = uiNode.props.width + "px";
        if (uiNode.props.height) el.style.height = uiNode.props.height + "px";
        break;
      case "icon":
        el = document.createElement("span");
        el.textContent = String(uiNode.props.name || "•");
        break;
      case "list_vertical":
      case "list_horizontal": {
        el = document.createElement("div");
        el.style.border = "1px solid #e0e0e0";
        el.style.borderRadius = "8px";
        el.style.padding = "8px";
        el.style.display = "flex";
        el.style.flexDirection = uiNode.type === "list_vertical" ? "column" : "row";
        el.style.gap = "8px";
        el.style.overflow = uiNode.type === "list_horizontal" ? "auto" : "visible";
        // items 绑定 → 数组；渲染时为每项复制 children 并注入 item/index 上下文。
        el._isListComponent = true;
        el._listUiNode = uiNode;
        break;
      }
      case "tab_container": {
        el = document.createElement("div");
        el.style.border = "1px solid #e0e0e0";
        el.style.borderRadius = "8px";
        el.style.overflow = "hidden";
        el._isTabComponent = true;
        el._tabUiNode = uiNode;
        el._tabIndex = 0;
        break;
      }
      default:
        // 插件提供的 UI 组件（type 以 "plugin_" 开头）。
        // v1 不在 Web 运行时解释执行 manifest 中的 renderFn（需要将节点
        // 解释器移植到 JS，工程量大）。此处渲染一个有意义的占位卡片：
        // 显示组件类型 + props 摘要，让用户感知组件存在。
        // 未来支持 renderFn 时，可在此处调用嵌入的函数 IR 生成 UiNode 子树
        // 并递归 renderNode。
        if (uiNode.type && uiNode.type.indexOf("plugin_") === 0) {
          el = document.createElement("div");
          el.setAttribute("data-type", uiNode.type);
          el.style.padding = "10px";
          el.style.margin = "4px 0";
          el.style.border = "1px dashed #9e9e9e";
          el.style.borderRadius = "8px";
          el.style.background = "rgba(0,0,0,0.03)";
          el.style.minHeight = "48px";
          const header = document.createElement("div");
          header.style.fontWeight = "600";
          header.style.fontSize = "13px";
          header.style.marginBottom = "4px";
          header.style.display = "flex";
          header.style.alignItems = "center";
          header.style.gap = "6px";
          const badge = document.createElement("span");
          badge.textContent = "插件";
          badge.style.fontSize = "10px";
          badge.style.padding = "1px 4px";
          badge.style.borderRadius = "3px";
          badge.style.background = "#e0e0e0";
          badge.style.color = "#424242";
          header.appendChild(badge);
          const nameSpan = document.createElement("span");
          // 去掉 "plugin_" 前缀作为显示名
          nameSpan.textContent = uiNode.type.substring(7);
          header.appendChild(nameSpan);
          el.appendChild(header);
          // 显示前 2 项 prop 摘要
          if (uiNode.props) {
            const propKeys = Object.keys(uiNode.props).slice(0, 2);
            if (propKeys.length > 0) {
              const summary = document.createElement("div");
              summary.style.fontSize = "11px";
              summary.style.color = "#616161";
              summary.style.fontFamily = "monospace";
              summary.textContent = propKeys
                .map(k => k + "=" + String(uiNode.props[k]))
                .join(" · ");
              el.appendChild(summary);
            }
          }
        } else {
          el = document.createElement("div");
          el.setAttribute("data-type", uiNode.type);
        }
    }
    el.setAttribute("data-ui-id", uiNode.id || "");

    // 应用 LayoutConfig（width/height/margin；位置由父容器布局算法计算）。
    applyLayout(el, uiNode, parent);
    // 应用 UiNode.style（视觉样式 map）。
    applyStyle(el, uiNode);

    // 应用静态 props
    if (uiNode.props) {
      Object.keys(uiNode.props).forEach(k => {
        if (k === "text" || k === "label" || k === "placeholder" || k === "src") return;
        // 其他 prop 由 case 内已处理
      });
    }

    // 应用绑定
    if (uiNode.bindings) {
      applyBindings(el, uiNode);
    }

    // 触发点：加载时（优先从 uiNode.triggers.onLoad 读取，兼容旧 props.onLoad）。
    var onLoadFn = (uiNode.triggers && uiNode.triggers.onLoad) || (uiNode.props && uiNode.props.onLoad);
    if (onLoadFn) {
      setTimeout(function() { triggerFunction(onLoadFn); }, 0);
    }

    // 入场动画：组件首次渲染时播放（applyEntranceAnimation 内部已延迟到下一帧）。
    applyEntranceAnimation(el, uiNode);
    // 触发动画：将 uiNode.animations.triggered 绑定到对应 DOM 事件。
    applyTriggeredAnimations(el, uiNode);

    // 子节点 / 容器组件渲染
    if (el._isListComponent) {
      renderListChildren(el, uiNode);
    } else if (el._isTabComponent) {
      renderTabChildren(el, uiNode);
    } else if (uiNode.children && uiNode.children.length > 0) {
      // 容器组件（slider/switch）向子节点注入组件上下文。
      if (el._componentContext) {
        pushComponentContext(el._componentContext);
      }
      // 子组件布局：布局强制开启，含 LayoutConfig 时按 9 宫格堆叠或绝对坐标定位；
      // 历史数据无 layout 时回退到默认垂直堆叠。
      if (childrenHaveAbsolute(uiNode.children)) {
        renderChildrenAbsolute(el, uiNode.children);
      } else if (childrenHaveLayout(uiNode.children)) {
        renderChildrenRelative(el, uiNode.children);
      } else {
        uiNode.children.forEach(function(child) {
          var childEl = renderNode(child, el);
          if (childEl) el.appendChild(childEl);
        });
      }
      if (el._componentContext) {
        popComponentContext();
      }
    }
    return el;
  }

  // 渲染列表子节点：按 items 绑定值展开，为每项复制 children 模板并注入 item/index。
  function renderListChildren(el, uiNode) {
    let items = [];
    if (uiNode.bindings && uiNode.bindings.items) {
      const v = readBindingValue(uiNode.bindings.items.ref);
      if (Array.isArray(v)) items = v;
    }
    // 注册列表组件，便于页面函数 outputs 就绪后重新渲染。
    if (uiNode.id) {
      LIST_REGISTRY.set(uiNode.id, { el: el, uiNode: uiNode });
    }
    // 清空已有子节点（重新渲染时使用）。
    while (el.firstChild) el.removeChild(el.firstChild);
    if (!uiNode.children || uiNode.children.length === 0) return;
    const template = uiNode.children[0]; // v1：取第一个子节点作为模板
    items.forEach((item, index) => {
      const ctx = { componentId: uiNode.id, fields: { item: item, index: index } };
      pushComponentContext(ctx);
      const cloned = JSON.parse(JSON.stringify(template));
      const childEl = renderNode(cloned, el);
      if (childEl) el.appendChild(childEl);
      popComponentContext();
    });
  }

  // 渲染 Tab 子节点：v1 仅渲染当前 Tab。
  function renderTabChildren(el, uiNode) {
    if (!uiNode.children || uiNode.children.length === 0) return;
    const idx = el._tabIndex || 0;
    if (idx >= uiNode.children.length) return;
    const ctx = { componentId: uiNode.id, fields: { tab: idx } };
    pushComponentContext(ctx);
    const childEl = renderNode(uiNode.children[idx], el);
    if (childEl) el.appendChild(childEl);
    popComponentContext();
  }

  function applyBindings(el, uiNode) {
    Object.keys(uiNode.bindings || {}).forEach(propName => {
      const binding = uiNode.bindings[propName];
      if (!binding || !binding.ref) return;
      // 初始值
      const value = readBindingValue(binding.ref);
      if (value !== undefined) {
        applyProp(el, propName, value);
      }
      // 注册到 binding registry（后续函数执行后回写）
      const id = uiNode.id;
      if (!BINDING_REGISTRY.has(id)) BINDING_REGISTRY.set(id, []);
      BINDING_REGISTRY.get(id).push({ el, propName, ref: binding.ref });
    });
  }

  function applyProp(el, propName, value) {
    switch (propName) {
      case "text":
      case "label":
        if (el.tagName === "BUTTON" || el.tagName === "SPAN") {
          el.textContent = String(value ?? "");
        }
        break;
      case "value":
        if (el.tagName === "INPUT") el.value = String(value ?? "");
        break;
      case "color":
        el.style.color = String(value);
        break;
      case "backgroundColor":
        el.style.backgroundColor = String(value);
        break;
      case "visible":
        el.style.display = value ? "" : "none";
        break;
      default:
        el.setAttribute("data-bind-" + propName, String(value));
    }
  }

  function readBindingValue(ref) {
    // Web 端初始只能读项目变量默认值
    if (ref.source === "projVar") {
      const v = (PROJECT.projectVars || []).find(v => v.id === ref.varId);
      return v ? v.defaultValue : undefined;
    }
    // 页面函数 outputs：按时间线状态返回（done=缓存值，其他=undefined 加载态占位）。
    if (ref.source === "funcVar" && ref.isPageFunc) {
      const entry = PAGE_FUNC_OUTPUTS.get(ref.funcId);
      if (entry && entry.state === "done" && entry.outputs) {
        return entry.outputs[ref.outputName];
      }
      return undefined; // running/idle/error → 加载态占位（undefined）。
    }
    if (ref.source === "funcVar") return undefined;
    if (ref.source === "upstream") return undefined;
    // 设备变量：Web 端初始即可解析（与 resolveDeviceProperty 一致）。
    if (ref.source === "device") {
      return resolveDeviceProperty(ref.property);
    }
    // 组件上下文变量：从栈中查找匹配的组件上下文，按 fieldName 取字段。
    // 形如 'item' / 'index' / 'value' / 'tab' / 'item.name'（嵌套字段用点分隔）。
    if (ref.source === "component") {
      const ctx = ref.componentId ? findComponentContext(ref.componentId) : null;
      if (!ctx) return undefined;
      return readComponentField(ctx, ref.fieldName);
    }
    return undefined;
  }

  // 解析组件上下文字段：支持 'item' / 'index' / 'item.name' 等点分隔路径。
  function readComponentField(ctx, fieldName) {
    if (!fieldName) return ctx.fields;
    const parts = String(fieldName).split(".");
    let cur = ctx.fields;
    for (const p of parts) {
      if (cur == null || typeof cur !== "object") return undefined;
      cur = cur[p];
    }
    return cur;
  }

  async function triggerFunction(funcIdOrName) {
    const fn = findFunction(funcIdOrName);
    if (!fn) {
      console.warn("[NodeVisual] Function not found: " + funcIdOrName);
      return;
    }
    const result = await runFunction(fn, {});
    if (result.error) {
      console.error("[NodeVisual] Function error:", result.error);
      return;
    }
    refreshBindings(result.outputs);
  }

  function refreshBindings(outputs) {
    // 简化：遍历 BINDING_REGISTRY，重新读取所有 binding（包含刚执行的输出）
    for (const [id, list] of BINDING_REGISTRY.entries()) {
      for (const b of list) {
        const v = readBindingValueAfterRun(b.ref, outputs);
        if (v !== undefined) applyProp(b.el, b.propName, v);
      }
    }
  }

  function readBindingValueAfterRun(ref, outputs) {
    if (ref.source === "upstream") {
      const k = ref.nodeId + "." + ref.outputName;
      return outputs ? outputs[k] : undefined;
    }
    return readBindingValue(ref);
  }

  // ====== 启动 ======
  async function boot() {
    const errEl = document.getElementById("boot-error");
    try {
      await loadIR();
      document.title = (PROJECT.meta && PROJECT.meta.name) || "NodeVisual App";
      renderUI();
      // 触发所有"应用启动"入口函数（kind=external, ref=app_start）
      if (PROJECT.functions) {
        for (const fn of PROJECT.functions) {
          if (fn.entry && fn.entry.kind === "external" && fn.entry.ref === "app_start") {
            triggerFunction(fn.id);
          }
        }
        // 触发所有页面 onLoad 函数（kind=pageEvent, ref=<pageId>:onLoad）。
        // v1 Web 端按声明序执行所有页面的 onLoad（单页应用按页面切换时
        // 也应触发，但 v1 简化为初始化时一次性触发首个页面）。
        const pages = (PROJECT.ui || []).filter(function(n) { return n && n.type === "page"; });
        const firstPageId = pages.length > 0 ? pages[0].id : null;
        for (const fn of PROJECT.functions) {
          if (!fn.entry || fn.entry.kind !== "pageEvent") continue;
          const ref = fn.entry.ref || "";
          const idx = ref.indexOf(":");
          if (idx <= 0) continue;
          const pageId = ref.substring(0, idx);
          const event = ref.substring(idx + 1);
          if (event !== "onLoad") continue;
          // v1 简化：仅触发首个页面的 onLoad；其他页面的 onLoad 在页面
          // 切换逻辑中触发（待后续实现 SPA 路由时补完）。
          if (firstPageId && pageId === firstPageId) {
            // 异步执行，失败不阻塞其他函数；outputs 缓存到 PAGE_FUNC_OUTPUTS。
            triggerPageFunction(fn);
          }
        }
      }
    } catch (e) {
      console.error("[NodeVisual] Boot failed:", e);
      if (errEl) errEl.textContent = "启动失败: " + e.message;
    }
  }

  // 页面级函数 outputs 缓存（已在文件顶部声明为 PAGE_FUNC_OUTPUTS）。

  async function triggerPageFunction(fn) {
    PAGE_FUNC_OUTPUTS.set(fn.id, { state: "running" });
    try {
      const result = await runFunction(fn, {});
      if (result.error) {
        PAGE_FUNC_OUTPUTS.set(fn.id, { state: "error", error: result.error });
      } else {
        PAGE_FUNC_OUTPUTS.set(fn.id, { state: "done", outputs: result.outputs || {} });
      }
      // 触发引用了此函数 outputs 的 UI 组件重新读取绑定。
      refreshBindingsForPageFunc(fn.id);
    } catch (e) {
      PAGE_FUNC_OUTPUTS.set(fn.id, { state: "error", error: String(e) });
    }
  }

  // 刷新依赖页面函数 outputs 的 UI 绑定（v1 简化：全部刷新）。
  function refreshBindingsForPageFunc(funcId) {
    BINDING_REGISTRY.forEach(entries => {
      for (const e of entries) {
        if (e.ref && e.ref.source === "funcVar" && e.ref.isPageFunc && e.ref.funcId === funcId) {
          const v = readBindingValue(e.ref);
          if (v !== undefined) applyProp(e.el, e.propName, v);
        }
      }
    });
    // 重新渲染依赖该函数 outputs 的列表组件（items 绑定可能引用页面函数 outputs）。
    LIST_REGISTRY.forEach(entry => {
      const uiNode = entry.uiNode;
      if (uiNode.bindings && uiNode.bindings.items) {
        const ref = uiNode.bindings.items.ref;
        if (ref && ref.source === "funcVar" && ref.isPageFunc && ref.funcId === funcId) {
          renderListChildren(entry.el, uiNode);
        }
      }
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
''';
  }

  /// 生成 index.html 内容（引用 runtime.js + ir.json + 提供 #app-root 容器）。
  static String indexHtml(String projectName) {
    final safeName = _escapeHtml(projectName);
    return '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>$safeName</title>
  <style>
    * { box-sizing: border-box; }
    html, body { margin: 0; padding: 0; height: 100%; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
    #app-root { min-height: 100vh; padding: 16px; }
    #boot-error { color: #c0392b; padding: 12px; }
    button { padding: 10px 16px; border: none; border-radius: 8px; background: #6200ee; color: white; cursor: pointer; font-size: 14px; }
    input { padding: 8px 12px; border: 1px solid #ccc; border-radius: 8px; font-size: 14px; }
  </style>
</head>
<body>
  <div id="app-root"></div>
  <div id="boot-error"></div>
  <script src="runtime.js"></script>
</body>
</html>
''';
  }

  /// README 内容（说明包结构）。
  static String readmeMd(String projectName) {
    return '''# $projectName - Web 产物

由 NodeVisual App Builder 端侧生成。

## 包结构
- \`index.html\` - 入口页面（任意浏览器打开即可运行）
- \`runtime.js\` - 节点图解释器 + UI 渲染器
- \`ir.json\` - 项目中间表示（IR）
- \`manifest.json\` - 构建清单
- \`README.md\` - 本文件

## 部署
将该目录整体上传到任意静态文件服务器（Nginx / GitHub Pages / Vercel 等），
或直接用浏览器打开 \`index.html\` 即可运行。
''';
  }

  static String _escapeHtml(String s) {
    return s
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
  }
}
